### ISSUE TITLE
Genes 

### ISSUE THREAD

**Issue by afitz-gmu** [Single-Cell-Genomics-Group-CNAG-CRG/Tumor-Immune-Cell-Atlas#12]
Hi, I am looking through the new matrix of genes x expression uploaded to zenodo. I am noticing that I can't find some genes in that file that are located in your shinyapp. When I pull out all the first column gene names it only totals 4419 genes. I am wondering if only some of the data was uploaded or if this is a known problem. 

Thanks!

**Comment by PaulaNietoG** [comment]
Hello! This is because the matrix only contains the integrated data. If you download the .rds or .h5ad files you will have the complete objects there. 
Thanks a lot for your interest in our work!

**Comment by afitz-gmu** [comment]
Hi, thanks so much for getting back to me. If I am looking for just one specific gene is there an easy way to manipulate these files for that gene? The files are so large that I'm having some issues. Thanks!

**Comment by PaulaNietoG** [comment]
Hello, unfortunately, no, there is no easy way... However, if you just want to check the expression of that gene, you can visualize it using [our Shiny App](https://singlecellgenomics-cnag-crg.shinyapps.io/TICA), otherwise if you need to extract raw/normalized counts for that gene(s), you will have to manipulate the whole object.
